choideakook/BaekJoon_Supporter

src/main/java/com/huh/BaekJoonSupporter/Comment.java

feat:comment entity

---

src/main/java/com/huh/BaekJoonSupporter/member/Member.java
src/main/java/com/huh/BaekJoonSupporter/member/MemberRepository.java

feat(Member Entity): 필드 구현

---

src/main/java/com/huh/BaekJoonSupporter/teamrule/TeamRule.java

TeamRule 엔티티 구현 했습니다.
속성명을 아래와 같이 변경하였습니다.
- 변동사항 : 'name'  -> 'ruleName'
- 변동사유 : Member 엔티티에 name과 중복이라 ruleName으로 변경했습니다.
검토부탁드립니당

feat: TeamRule entity

---

build.gradle
src/main/java/com/huh/BaekJoonSupporter/Line/Line.java
src/main/java/com/huh/BaekJoonSupporter/Line/LineRepository.java
src/main/java/com/huh/BaekJoonSupporter/Line/LineService.java

3/29  23:48
- 작성자 : 김동우(DongWooKim97)
- 완료사항 : `Line` 엔티티 작성완료
- 고려사항 : 추후에 변경가능성 존재
---------
<br>
3/29 23:59
- 추가커밋(chore) : main의 gradle을 임의로 수정했었는데, main의 gradle상태로 다시 롤백시킴

feat: create Line entity

---

src/main/java/com/huh/BaekJoonSupporter/team/Team.java
src/main/java/com/huh/BaekJoonSupporter/team/TeamService.java

- 완료 : 
Team, TeamService 수정
- 참고 : 
TeamService 미완

feat: team service enhancement

---

src/main/java/com/huh/BaekJoonSupporter/line/Line.java
src/main/java/com/huh/BaekJoonSupporter/line/LineController.java
src/main/java/com/huh/BaekJoonSupporter/line/LineRepository.java
src/main/java/com/huh/BaekJoonSupporter/line/LineService.java

fix: line dir add

---

src/main/java/com/huh/BaekJoonSupporter/teamrule/TeamRule.java

- 완료 : teamRule 에서 import 수정
(team 임포트 패키지 수정)
- 참고 : 
- teamRule CRUD 기능

fix : teamRule에서 import ììimport 수정

---

.gitignore
build.gradle

feat: ignore 추가

---

src/main/java/com/huh/BaekJoonSupporter/member/Member.java
src/main/java/com/huh/BaekJoonSupporter/member/MemberRepository.java
src/main/java/com/huh/BaekJoonSupporter/member/MemberService.java

- 완료 : 레포지터리에 있던 오타를 수정했습니다(findByMemberName -> findByName)
- 엔티티의 token 필드에 unique 옵션을 추가했습니다.
- 참고 : 
- CRUD 테스트

fix:MemberRepository findByMemberName -> findByName

---

src/main/java/com/huh/BaekJoonSupporter/board/Board.java
src/main/java/com/huh/BaekJoonSupporter/board/BoardService.java
src/test/java/com/huh/BaekJoonSupporter/board/BoardServiceTest.java

- 완료 : 
-  @Builder 어노테이션 toBuilder 추가
- Service 계층 모든 method 검증 완료 : 모든 로직 정상 작동 확인됬습니다.
- Service 계층 오류 수정 : test 를 하면서 잘못되었었던 로직 수정
- 참고 : 
- Board Service 의 method 를 사용하기 위해선 member 객체가 필요합니다.
- member 의 @Builder 어노테이션 최신화와, modify 수정 전까지 Board Service 메서드를 사용할경우 오류가 발생하게 됩니다.
- Boarder Controller
- 게시판 목록 페이지 개발
Close #19

BoardServiceTest 모든 로직 검증완료 이상없습니다

---

src/main/java/com/huh/BaekJoonSupporter/teamrule/TeamRule.java
src/main/java/com/huh/BaekJoonSupporter/teamrule/TeamRuleController.java
src/main/java/com/huh/BaekJoonSupporter/teamrule/TeamRuleRepository.java
src/main/java/com/huh/BaekJoonSupporter/teamrule/TeamRuleService.java

- 완료 : TeamRule CRUD 구현 (Test 전)
- 참고 : 
- Test를 추후 진행하도록 하겠습니다!

feat:TeamRule CRUD 구현(Test전)

---

src/main/java/com/huh/BaekJoonSupporter/SecurityConfig.java
src/main/java/com/huh/BaekJoonSupporter/comment/Comment.java
src/main/java/com/huh/BaekJoonSupporter/comment/CommentController.java
src/main/java/com/huh/BaekJoonSupporter/comment/CommentForm.java
src/main/java/com/huh/BaekJoonSupporter/comment/CommentService.java
src/test/java/com/huh/BaekJoonSupporter/comment/CommentServiceTest.java

- 완료 : 
Controller (modify(get) 수정) 
Service(@Transactional 추가 ,create() add 추가, modify() toBuilder 수정) 
Security Config 추가 html 작업 편의상 (“/“)로 설정
- 참고 : 
- api or 크롤링

feat: Security Config

---

src/main/java/com/huh/BaekJoonSupporter/comment/CommentController.java
src/main/java/com/huh/BaekJoonSupporter/comment/CommentRepository.java
src/main/java/com/huh/BaekJoonSupporter/comment/CommentService.java
src/test/java/com/huh/BaekJoonSupporter/comment/CommentServiceTest.java

- 완료 : 
comment 댓글 생성, 수정, 삭제  약식 테스트케이스 작성
- 참고 : 
-

feat: commentTest 

---

src/main/java/com/huh/BaekJoonSupporter/member/Member.java
src/main/java/com/huh/BaekJoonSupporter/member/MemberService.java

- 완료
- Member 엔티티에 toBuilder = true 옵션과 @Builder.Default를 추가하였습니다.
- MemberService의 modify 메서드에서 builder -> toBuilder로 수정하고 Member.name은 변경이 안 되도록 삭제했습니다.
- 테스트 구현

fix: member 엔티티 builder 옵션 수정, modify 메서드 수정

---

src/main/java/com/huh/BaekJoonSupporter/board/BoardController.java
src/main/java/com/huh/BaekJoonSupporter/board/initDB/InitDB.java
src/main/resources/templates/board/boardList.html
src/main/resources/templates/board/boardTemplate/getBoard.html
src/main/resources/templates/board/create.html
src/main/resources/templates/navbar.html

- 완료 : 
- 게시판 수정, 삭제기능 구현
- 네비바에 board 링크 추가 (게시판 리스트로 이동함)
- 페이징 작동안되는 문제 해결 (css 추가)
- 참고 : 
- 게시판의 crud 아직 권한과 검증 구현 안되어있습니다.
- 추후에 로그인 기능 추가되면 구현하겠습니다.
- 게시판 카테고리 구현
Close #51

게시판 수정 삭제 구현 / 네비바 board 누르면 게시판 메인 이동 / 페이징 버그 픽스

---

src/main/java/com/huh/BaekJoonSupporter/board/Board.java
src/main/java/com/huh/BaekJoonSupporter/board/BoardController.java
src/main/java/com/huh/BaekJoonSupporter/board/BoardRepository.java
src/main/java/com/huh/BaekJoonSupporter/board/BoardService.java
src/main/java/com/huh/BaekJoonSupporter/board/form/BoardCreateForm.java
src/main/java/com/huh/BaekJoonSupporter/board/initDB/InitDB.java
src/main/java/com/huh/BaekJoonSupporter/category/Category.java
src/main/java/com/huh/BaekJoonSupporter/category/CategoryController.java
src/main/java/com/huh/BaekJoonSupporter/category/CategoryRepository.java
src/main/java/com/huh/BaekJoonSupporter/category/CategoryService.java
src/main/java/com/huh/BaekJoonSupporter/category/form/CategoryForm.java
src/main/resources/templates/board/boardList.html
src/main/resources/templates/board/boardTemplate/getBoard.html
src/main/resources/templates/board/create.html
src/main/resources/templates/category/create.html
src/main/resources/templates/category/list.html
src/main/resources/templates/navbar.html
src/test/java/com/huh/BaekJoonSupporter/category/CategoryServiceTest.java

- 완료 : 
- 카테고리 entity ~ service crud 구현 / 테스트 완료
- 카테고리 페이지 구현 
- 카테고리별 게시물 리스트 조회 구현
- 모든 게시물 리스트 조회 구현
- 네비바에 카테고리 리스트 바로가기 메뉴 추가
- 네비바 기존 board 버튼은 전체 게시물 조회로 이동하기 변경
- 카테고링 등록기능 구현
- 카테고리 init data 추가
<br>
- 참고 : 
- 카테고리에 속하지 않은 게시물은 모든 게시물 리스트 조회에서 확인 가능
- 게시물 등록시 카테고리를 선택할 수 있는기능은 구현해야함
<br>
- 카테고리별 게시물 등록기능 구현
- 카테고리 수정기능 구현
- 카테고리 삭제기능 구현

게시글을 분류할 수 있는 카테고리 도메인 구현

---

src/main/java/com/huh/BaekJoonSupporter/teamrule/TeamRule.java
src/main/java/com/huh/BaekJoonSupporter/teamrule/TeamRuleController.java
src/main/java/com/huh/BaekJoonSupporter/teamrule/TeamRuleRepository.java
src/main/java/com/huh/BaekJoonSupporter/teamrule/TeamRuleService.java
src/main/resources/templates/teamrule/create.html
src/test/java/com/huh/BaekJoonSupporter/teamrule/TeamRuleServiceTest.java

✅ 수정 사항 요약
완료 : TeamRule 엔티티 속성 변경
(String 1개 -> 목표 구분(문제 수/ 난이도별 문제 수), 난이도 설정, 목표 개수
*** 충돌 수정하여 다시 올립니당!**
참고 :
✅ 다음 계획
HTML에서 난이도 상관없이 문제 선택할 경우 난이도 선택하는 박스 안나오게 전처리 기능 구현(자바스크립트), 해보겠습니다..
동작 확인했으나 혹시 모를 수정사항 다시 점검

feat : teamrule 엔티티 수정 및 create 테스트

---

src/main/java/com/huh/BaekJoonSupporter/member/MemberCreateForm.java
src/main/java/com/huh/BaekJoonSupporter/member/MemberService.java
src/main/resources/templates/member/login_form.html
src/main/resources/templates/member/signup_form.html
src/test/java/com/huh/BaekJoonSupporter/member/MemberServiceTest.java

- 완료 : 
- signup_form 새로 작성했습니다.
- login_form에서 아이디와 비밀번호를 올바르게 입력했는지 체크하는 script를 추가했습니다.
- MemberServiceTest 새로 작성했습니다.
- 참고 : 
- initDB에서 계속 BeanCreationException이 터져서 제대로 실행해보지는 못했습니다 ㅠㅠ
- 일단 작업해둔 부분 먼저 올려놓고 오류 해결되면 실행해보겠습니다.
-

feat: signup_form 작성 및 MemberServiceTest

---

src/main/java/com/huh/BaekJoonSupporter/board/initDB/InitDB.java
src/main/resources/application.yml
src/test/java/com/huh/BaekJoonSupporter/board/BoardServiceTest.java
src/test/java/com/huh/BaekJoonSupporter/category/CategoryServiceTest.java

게시물과 카테고리 테스트명을 한글로 변경했습니다.

---

src/main/java/com/huh/BaekJoonSupporter/teamrule/TeamRuleController.java
src/main/java/com/huh/BaekJoonSupporter/teamrule/TeamRuleCreateForm.java
src/main/java/com/huh/BaekJoonSupporter/teamrule/TeamRuleRepository.java
src/main/java/com/huh/BaekJoonSupporter/teamrule/TeamRuleService.java
src/test/java/com/huh/BaekJoonSupporter/teamrule/TeamRuleServiceTest.java

✅ 수정 사항 요약
완료 : TeamRule 엔티티 속성 변경으로 인한 Service 메소드 변경 + 테스트케이스 변경
(Read를 TeamId로 할까 했는데, repository에서 바로 안되네요 mapped by를 안해서 그런가 싶기도 한데..)
참고 :
✅ 다음 계획
계획 입력받는 폼 HTML 도전 해보겠습니당

feat : TeamRule CRUD수정 및 테스트케이스 추가

---

src/main/java/com/huh/BaekJoonSupporter/team/TeamController.java
src/main/resources/templates/team/add.html
src/main/resources/templates/team/create.html
src/main/resources/templates/team/modify.html
src/main/resources/templates/team/team_info.html

- 완료 : 
- team html(create, info, modify, add) 파일 추가
- 위 html 맵핑으로 TeamController 수정
- 참고 : 
- 팀 설명 내용 추가 => Team Entity

feat: TeamController modify, html add

---

src/main/resources/templates/member/login_form.html
src/main/resources/templates/member/me.html
src/main/resources/templates/member/signup_form.html

- 완료 : 
- login_form, signup_form 수정했습니다.
- me.html 내용 추가했습니다. 기본 뼈대만 만들어놓았습니다.
- 참고 : 
-

member 관련 html 파일 수정 및 추가

---

src/main/java/com/huh/BaekJoonSupporter/team/Team.java

- 완료 : 
- Team 클래스 details(팀 설명) 필드 추가
- teamRules 필드 OneToMany(mappedBy = "team") 수정
- OneToMany 관계 ToString.Exclude 추가
- 참고 : 
- TeamController 세부기능 테스트

feat: Team Entity modify
